name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "161024.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "161024.xyz"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "not-docker.161024.xyz", custom_domain = true },
  { pattern = "not-quay.161024.xyz", custom_domain = true },
  { pattern = "not-gcr.161024.xyz", custom_domain = true },
  { pattern = "not-k8s-gcr.161024.xyz", custom_domain = true },
  { pattern = "not-k8s.161024.xyz", custom_domain = true },
  { pattern = "not-ghcr.161024.xyz", custom_domain = true },
  { pattern = "not-cloudsmith.161024.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "not-docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
